name: refract
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytorch>=2.3.0
  - torchvision
  - pytorch-cuda=12.1
  - pyg
  - pip:
    - torch-scatter
    - torch-sparse
    - -e ".[dev,umap]"
